name: Java Library CI2

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Do CI Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - id: gradle_build
        name: Execute Gradle build
        run: ./gradlew build